# Generated by Django 3.2 on 2022-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatestinvestapp', '0002_maximum_withdrawal_minimum_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='running_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
